# Generated by Django 5.0.6 on 2024-06-06 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post_man", "0003_ordermodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=50, unique=True)),
                ("customer_name", models.CharField(max_length=100)),
                ("door_number", models.CharField(max_length=20)),
                ("apartment_number", models.CharField(max_length=20)),
                ("street_address", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("pincode", models.CharField(max_length=10)),
                ("phone_number", models.CharField(max_length=20)),
                ("ring_bell", models.BooleanField()),
                ("google_link", models.CharField(max_length=255)),
                ("landmark", models.CharField(max_length=100)),
                ("order_weight", models.DecimalField(decimal_places=2, max_digits=5)),
                ("item_type", models.CharField(max_length=100)),
                ("battery_included", models.BooleanField()),
                ("expected_delivery_date", models.DateField()),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            ("two_hours", "two_hours"),
                            ("one_day", "one_day"),
                            ("super_fast", "super_fast"),
                            ("normal", "normal"),
                        ]
                    ),
                ),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("delivered", "Delivered"),
                            ("damaged", "Damaged"),
                            ("customer_not_reachable", "Customer Not Reachable"),
                            ("customer_rejects", "Customer Rejects"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="OrderModel",
        ),
    ]
