# Generated by Django 5.0.6 on 2024-06-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("post_man", "0004_order_delete_ordermodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("delivered", "Delivered"),
                    ("damaged", "Damaged"),
                    ("customer_not_reachable", "Customer Not Reachable"),
                    ("customer_rejects", "Customer Rejects"),
                    ("available", "Available"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="priority",
            field=models.CharField(
                choices=[
                    ("two_hours", "two_hours"),
                    ("one_day", "one_day"),
                    ("super_fast", "super_fast"),
                    ("normal", "normal"),
                ],
                max_length=100,
            ),
        ),
    ]
